### ISSUE TITLE
May I ask what your file directory looks like?

### ISSUE THREAD

**Issue by yun189** [invictus717/MiCo#1]

**Comment by invictus717** [comment]
please see this [doc](https://github.com/invictus717/MiCo/tree/master/data).

**Comment by invictus717** [comment]
If you want to inference the pretrained model, you can directly download the google drive folder to the current directory.

**Comment by yun189** [comment]
i have read readme,but "pretrain_path='MiCo-g'" made me confused

**Comment by invictus717** [comment]
You can directly download the google drive folder to the current directory, the pretrained models are zipped in the "MiCo-g" folder on my google drive.

**Comment by yun189** [comment]
Sorry, I cannot find ‘MiCo-g’ folder on google driver, although I find ‘MiCo-g’ in your code.

**Comment by invictus717** [comment]
Sorry, I just found that it's named "MiCo" on the google drive...You can simply rename the folder and run the inference code.

**Comment by yun189** [comment]
ohh,i got it. thanks for your answer

**Comment by invictus717** [comment]
Thanks for your efforts! I will also update this in the README.md soon
