### ISSUE TITLE
would you make requirements.txt public？

### ISSUE THREAD

**Issue by yun189** [invictus717/MiCo#4]
Some errors happened:
torchvision 0.18.1 requires torch==2.3.1, but you have torch 2.3.0 which is incompatible.
xformers 0.0.26.post1 requires torch==2.3.0, but you have torch 2.3.1 which is incompatible.
So what can i do for this error?

**Comment by invictus717** [comment]
You may run this script:

https://github.com/invictus717/MiCo/blob/master/set_env.sh

**Comment by yun189** [comment]
thanks!
